version: '3.8'

services:  
  backend:    
    build:      
      context: ./backend    
    ports:      
      - "3000:3000"    
    env_file:      
      - ./backend/.env    
    volumes:      
      - ./backend:/usr/src/app    
    working_dir: /usr/src/app  
    
  frontend:    
    build:      
      context: ./frontend    
    ports:      
      - "8080:8080"    
    volumes:      
      - ./frontend:/usr/src/app    
    working_dir: /usr/src/app